"""One-off script to add missing Oxford and Cambridge courses scraped from web sources."""

import csv
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"

COMMON_OXFORD = {
    "university": "University of Oxford",
    "degree_level": "Degree level: Undergraduate",
    "study_mode": "Full-time",
    "provider_url": "https://www.ox.ac.uk/",
    "description": "",
}

oxford_courses = [
    # STEM: A*A*A
    {
        "course": "Chemistry",
        "ucas_code": "F100",
        "duration": "4 years",
        "alevel_grades": "A*A*A",
        "alevel_details": "A*A*A with both A*s in science or maths subjects. Required: Chemistry and Maths.",
        "ib_points_raw": "40",
        "ib_points_numeric": 40.0,
        "ib_details": "40 points with 776 at Higher Level including Chemistry and Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/chemistry",
        "qualification": "Master of Chemistry (with Honours) - MChem (Hon)",
    },
    {
        "course": "Engineering Science",
        "ucas_code": "H100",
        "duration": "4 years",
        "alevel_grades": "A*A*A",
        "alevel_details": "A*A*A with the A*s in Maths, Further Maths or Physics. Required: Maths and Physics.",
        "ib_points_raw": "40",
        "ib_points_numeric": 40.0,
        "ib_details": "40 points with 776 at Higher Level including Maths and Physics.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/engineering-science",
        "qualification": "Master of Engineering (with Honours) - MEng (Hon)",
    },
    {
        "course": "Mathematics",
        "ucas_code": "G100",
        "duration": "4 years",
        "alevel_grades": "A*A*A",
        "alevel_details": "A*A*A with A*s in Mathematics and Further Mathematics if taken.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/mathematics",
        "qualification": "Master of Mathematics (with Honours) - MMath (Hon)",
    },
    {
        "course": "Mathematics And Computer Science",
        "ucas_code": "GG14",
        "duration": "4 years",
        "alevel_grades": "A*A*A",
        "alevel_details": "A*A*A with A*s in Maths and Further Maths if available.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/mathematics-and-computer-science",
        "qualification": "Master of Mathematics and Computer Science (with Honours) - MMathCompSci (Hon)",
    },
    {
        "course": "Mathematics And Philosophy",
        "ucas_code": "GV15",
        "duration": "4 years",
        "alevel_grades": "A*A*A",
        "alevel_details": "A*A*A with A* in Mathematics.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/mathematics-and-philosophy",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Mathematics And Statistics",
        "ucas_code": "GG13",
        "duration": "4 years",
        "alevel_grades": "A*A*A",
        "alevel_details": "A*A*A with A*s in Mathematics and Further Mathematics if available.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/mathematics-and-statistics",
        "qualification": "Master of Mathematics (with Honours) - MMath (Hon)",
    },
    # STEM: A*AA
    {
        "course": "Biology",
        "ucas_code": "C100",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA with A* in a science or Maths. Required: Biology and either Chemistry, Physics or Maths.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Biology.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biology",
        "qualification": "Master of Biology (with Honours) - MBiol (Hon)",
    },
    {
        "course": "Biochemistry",
        "ucas_code": "C700",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA including Chemistry and another science or Maths. A* in a science or Maths.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Chemistry.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biochemistry-molecular-and-cellular",
        "qualification": "Master of Biochemistry (with Honours) - MBiochem (Hon)",
    },
    {
        "course": "Biomedical Sciences",
        "ucas_code": "BC98",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA. Required: Two from Biology, Chemistry, Maths and Physics.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biomedical-sciences",
        "qualification": "Master of Biomedical Sciences (with Honours) - MBiomedSci (Hon)",
    },
    {
        "course": "Computer Science",
        "ucas_code": "G400",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA including A* in Maths. Further Maths recommended.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/computer-science",
        "qualification": "Master of Computer Science (with Honours) - MCompSci (Hon)",
    },
    {
        "course": "Computer Science And Philosophy",
        "ucas_code": "IV15",
        "duration": "3 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA including A* in Maths.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/computer-science-and-philosophy",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Earth Sciences",
        "ucas_code": "F600",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA. Required: Maths and either Chemistry or Physics.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/earth-sciences",
        "qualification": "Master of Earth Sciences (with Honours) - MEarthSci (Hon)",
    },
    {
        "course": "Materials Science",
        "ucas_code": "FJ22",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA with A* in Maths, Physics or Chemistry. Required: Maths and Physics.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Maths and Physics.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/materials-science",
        "qualification": "Master of Engineering (with Honours) - MEng (Hon)",
    },
    {
        "course": "Physics",
        "ucas_code": "F303",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA with A* in Physics, Maths or Further Maths. Required: Physics and Maths.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Physics and Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/physics",
        "qualification": "Master of Physics (with Honours) - MPhys (Hon)",
    },
    {
        "course": "Physics And Philosophy",
        "ucas_code": "FV35",
        "duration": "4 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA with A* in Physics or Maths. Required: Physics and Maths.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level including Physics and Maths.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/physics-and-philosophy",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    # Non-STEM missing courses (Languages, Humanities, etc.)
    {
        "course": "Classics And Modern Languages",
        "ucas_code": "QR89",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: A classical language (Latin or Greek) and a modern language.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/classics-and-modern-languages",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Classics And Asian And Middle Eastern Studies",
        "ucas_code": "QT89",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: Latin or Ancient Greek.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/classics-and-asian-and-middle-eastern-studies",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "English And Modern Languages",
        "ucas_code": "QR13",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: English and a modern language.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/english-and-modern-languages",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "European And Middle Eastern Languages",
        "ucas_code": "TR89",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: A modern language.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/european-and-middle-eastern-languages",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Ancient And Modern History",
        "ucas_code": "V110",
        "duration": "3 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/ancient-and-modern-history",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "History And Modern Languages",
        "ucas_code": "RV11",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: A modern language.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/history-and-modern-languages",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Law",
        "ucas_code": "M100",
        "duration": "3 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/law",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Modern Languages",
        "ucas_code": "R900",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: A modern language.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/modern-languages",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Modern Languages And Linguistics",
        "ucas_code": "QR19",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: A modern language.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/modern-languages-and-linguistics",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Oriental Studies",
        "ucas_code": "T600",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/asian-and-middle-eastern-studies",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Philosophy And Modern Languages",
        "ucas_code": "VR51",
        "duration": "4 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA. Required: A modern language.",
        "ib_points_raw": "38",
        "ib_points_numeric": 38.0,
        "ib_details": "38 points with 666 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/philosophy-and-modern-languages",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Philosophy, Politics And Economics",
        "ucas_code": "L0V0",
        "duration": "3 years",
        "alevel_grades": "AAA",
        "alevel_details": "AAA.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/philosophy-politics-and-economics",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Experimental Psychology",
        "ucas_code": "C830",
        "duration": "3 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/psychology-experimental",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
    {
        "course": "Psychology, Philosophy, And Linguistics",
        "ucas_code": "CV85",
        "duration": "3 years",
        "alevel_grades": "A*AA",
        "alevel_details": "A*AA.",
        "ib_points_raw": "39",
        "ib_points_numeric": 39.0,
        "ib_details": "39 points with 766 at Higher Level.",
        "course_url": "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/psychology-philosophy-and-linguistics",
        "qualification": "Bachelor of Arts (with Honours) - BA (Hons)",
    },
]

HEADERS = [
    "university", "course", "ucas_code", "degree_level", "study_mode",
    "duration", "alevel_grades", "alevel_details", "ib_points_raw",
    "ib_points_numeric", "ib_details", "course_url", "provider_url",
    "description", "qualification",
]


def main():
    csv_path = DATA_DIR / "courses.csv"

    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS)
        for c in oxford_courses:
            row = {**COMMON_OXFORD, **c}
            writer.writerow(row)

    print(f"Added {len(oxford_courses)} Oxford courses to {csv_path}")


if __name__ == "__main__":
    main()
